### ISSUE TITLE
Feature- add try on playground for logical functions on the site

### ISSUE THREAD

**Issue by singla-shivam** [Jozty/website#25]
There are logical functions like- and, or, both etc. We need to add a link- "Try on playground"

Rendered Example- https://fae.jozty.io/docs#add

File to add- https://github.com/Jozty/website/blob/master/content/all.md
Code example- https://github.com/Jozty/website/blob/master/content/all.md?plain=1#L117

**Comment by neelra8n** [comment]
I'd like to work on it.

**Comment by singla-shivam** [comment]
Closing it as we are moving examples to Fae.
